myvote/myvote/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vote/', include('vote.urls'))
]

myvote/vote/urls.py
from django.conf.urls import url

from. import views

app_name = 'vote'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

myvote/vote/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        #날짜가 최신일때만 true return
        #return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)
        return now - datetime.timedelta(days = 1) <= self.pub_date <= now
                                #오늘          -  하루
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    #fk로 묶인 객체가 삭제되었을시 연동하여 삭제
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text

myvote/vote/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.http import HttpResponse
from .models     import Question
from django.views import generic
from django.utils import timezone
class IndexView(generic.ListView):
    template_name = 'vote/index.html'
    context_object_name = 'latest_question_list' #parameter로 넘길 값 지정

    def get_queryset(self):     #overiding
        return Question.objects.filter(pub_date__lte = timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'vote/detail.html'

class ResultsView(generic.DeleteView):
    model = Question
    template_name = 'vote/results.html'

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    #orderby 안에 - 를 붙이면 desc 내림차순으로 정렬함
    context = {'latest_question_list' : latest_question_list}
    return render(request, 'vote/index.html', context)

#def results(request, question_id):
#    question = get_object_or_404(Question, pk = question_id)
#    return render(request, 'vote/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
        #input type = "submit"의 name의 value를 가지고 옴
    except:
        return render(request, 'vote/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return redirect('vote:results', pk = question.id )
#def detail(request, question_id):
#    question = get_object_or_404(Question, pk = question_id)
#    return render(request, 'vote/detail.html', {'question': question})

myvote/vote/templates/vote/detail.html
<h2> {{ question }} </h2>
{% if error_message %} <p><strong>{{ error_message }} </strong></p>
{% endif %}

<form action="{% url 'vote:vote' question.id %}" method="POST">
  {% csrf_token %}
  {% for choice in question.choice_set.all%}
    <input type="radio" name="choice" id="choice{{ forloop.count }}" value="{{ choice.id }}" />
    <!-- name = post의 dictionary처럼 쓸 수 있음 -->
    <label ofr="choice{{forloop.counter}}"> {{choice.choice_text}} </label><br>
  {% endfor %}
    <input type="submit" value="투표하기">
</form>

myvote/vote/templates/vote/index.html
{% extends 'vote/base.html' %}
{% block content %}
{% load static %}
<link rel = "stylesheet" type-"text/css" href="{% static 'vote/style.css' %}" />
{% if latest_question_list %}
  <ul>
    {% for question in latest_question_list %}
      <li><a href = "{% url 'vote:detail' question.id %}">{{ question.question_text}}</li>
    {% endfor %}
  </ul>
{% else %}
  <p>투표가 없습니다</p>
{% endif %}
{% end block content %}

myvote/vote/templates/vote/results.html
<h1>{{question.question_text}}</h1>

<ul>
  {% for choice in question.choice_set.all  %}
    <li> {{choice.choice_text}} -- {{choice.votes}} 득표 </li>
  {% endfor %}
</ul>

<a href="{% url 'vote:detail' question.id %}"> 다시 투표하기 </a>